version: 2
jobs:
  build:
    docker:
      - image: node:latest
    branches:
      only:
        - master
    steps:
      - checkout
      - run: yarn build
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Install Docker client
          command: |
            set -x
            VER="17.03.0-ce"
            curl -L -o /tmp/docker-$VER.tgz https://download.docker.com/linux/static/stable/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin
      - run: |
          TAG=latest
          docker build -t ajris/site:$TAG .
          docker login -u $DOCKER_USER -p $DOCKER_PASS
          docker push ajris/site:$TAG