version: 2
jobs:
  build:
    docker:
      - image: node:11-alpine
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: BUILDING
          command: yarn install
      - run:
          name: TESTING
          command: yarn test

  sonar:
    docker:
      - image: ajris/sonar:latest
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Upload to SonarCloud
          command: |
            ./sonar-scanner-3.3.0.1492-linux/bin/sonar-scanner -Dsonar.host.url=https://sonarcloud.io -Dsonar.projectKey=Ajris_site -Dsonar.organization=ajris-github -Dsonar.sources=. -Dsonar.login=$SONAR_LOGIN_KEY

  deploy_to_docker:
    machine: true
    steps:
      - checkout
      - run: |
          TAG=latest
          docker build -t ajris/site:$TAG .
          docker login -u $DOCKER_USER -p $DOCKER_PASS
          docker push ajris/site:$TAG

workflows:
  version: 2
  build_test_deploy_to_docker:
    jobs:
#      - build
      - sonar
#          requires:
#            - build
#      - deploy_to_docker:
#          requires:
#            - build